# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: es-VE # ¡Bien! Ya lo tienes en español de Venezuela.

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Caracas # Ejemplo para Venezuela. Busca tu zona horaria específica si es diferente.

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Omar Projects # El título principal de tu sitio. ¡Ya lo tienes!

tagline: Proyectos, herramientas y recursos para compartir # Un subtítulo o lema. ¡Personalízalo!

description: >- # Usado para SEO y el feed Atom.
  Un sitio para descargar y compartir proyectos, herramientas y recursos desarrollados por Omar. Explora tutoriales, software y más. # Sé descriptivo para los motores de búsqueda.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url:
  "https://www.omarprojects.site" # IMPORTANTE: Si usas un repositorio de proyecto (ej. aricagua.github.io/mi-blog-chirpy), esta es la URL base de tu GitHub Pages.
  # Si tu repositorio se llama `aricagua.github.io`, entonces aquí también iría "https://aricagua.github.io"

github:
  username: aricagua # ¡Cambia esto a tu nombre de usuario de GitHub!

twitter:
  username: tuUsuarioTwitter # Cambia esto a tu nombre de usuario de Twitter, si tienes. Si no, puedes borrar la línea o dejarla vacía.

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Omar Andrade # ¡Tu nombre completo! (O como quieras que aparezca)
  email: omar.andrade.developer@gmail.com # Tu correo electrónico, si quieres que sea público.
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/aricagua # Enlace a tu perfil de GitHub. ¡Actualízalo!
    - https://twitter.com/tuUsuarioTwitter # Enlace a tu perfil de Twitter, si tienes.
    # Uncomment below to add more social links
    # - https://www.linkedin.com/in/tuUsuarioLinkedIn # Si tienes LinkedIn, por ejemplo.

# Site Verification Settings (Opcional, para verificar tu sitio con motores de búsqueda)
webmaster_verifications:
  google: # tu-codigo-de-verificacion-google
  bing: # tu-codigo-de-verificacion-bing
  # alexa:
  # yandex:
  # baidu:
  # facebook:

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings (Opcional, si usas alguna herramienta de analítica)
analytics:
  google:
    id: # UA-XXXXXXXXX-Y o G-XXXXXXXXXX (tu ID de Google Analytics)
  # goatcounter:
  #   id:
  # umami:
  #   id:
  #   domain:
  # matomo:
  #   id:
  #   domain:
  # cloudflare:
  #   id:
  # fathom:
  #   id:

# Page views settings (Opcional, si quieres mostrar contador de visitas. GoatCounter es una opción)
pageviews:
  provider: # déjalo vacío si no lo usas

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light — Use the light color scheme
#     dark — Use the dark color scheme
#
theme_mode: # Déjalo vacío para que siga las preferencias del sistema y permita el cambio. O elige 'light' o 'dark'.

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn: # Déjalo vacío por ahora, a menos que sepas que necesitas un CDN específico para tus imágenes/medios.

# the avatar on sidebar, support local or CORS resources
avatar:
  /assets/img/profile_picture.png # Ejemplo. Coloca una imagen en `assets/img/profile_picture.png` (o la ruta que prefieras) y actualiza aquí.
  # Debe empezar con `/` si está en tu repositorio.

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image:
  /assets/img/social_preview.png # Ejemplo. Una imagen que se usará cuando compartas enlaces en redes sociales.
  # Colócala en `assets/img/social_preview.png` y actualiza aquí.

# boolean type, the global switch for TOC in posts.
toc: true # ¡Bien! Tabla de contenidos activada para posts.

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: giscus # O 'utterances' o 'disqus'. Giscus y Utterances son buenas opciones basadas en GitHub Issues/Discussions.
  # The provider options are as follows:
  disqus:
    shortname: # tu-disqus-shortname (si usas Disqus)
  # utterances settings › https://utteranc.es/
  utterances:
    repo: aricagua/mi-blog-chirpy # <tu-usuario-github>/<tu-repositorio-del-blog> (si usas Utterances)
    issue_term: pathname # O 'url', 'title', etc. 'pathname' suele ser una buena opción.
  # Giscus options › https://giscus.app
  giscus:
    repo: aricagua/mi-blog-chirpy # <tu-usuario-github>/<tu-repositorio-del-blog> (si usas Giscus)
    repo_id: # Obtén esto de la configuración de Giscus.app
    category: # Nombre de la categoría de Discussions en tu repo donde se crearán los comentarios.
    category_id: # Obtén esto de la configuración de Giscus.app
    mapping: pathname # 'pathname' es común.
    strict: "0"
    input_position: bottom
    lang: es # Para que la interfaz de Giscus esté en español.
    reactions_enabled: "1"

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: false # Déjalo en `false` a menos que quieras alojar los assets de Chirpy tú mismo. El CDN por defecto funciona bien.
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    # env: # [development | production]

pwa:
  enabled: true # Progressive Web App. ¡Buena opción!
  cache:
    enabled: true # Caché para PWA.
    deny_paths:
      # - "/example"

paginate: 10 # Número de posts por página en la lista de blog.

# The base URL of your site
baseurl:
  "/omarprojects" # IMPORTANTE: Si tu repositorio se llama `mi-blog-chirpy` y se sirve desde `aricagua.github.io/mi-blog-chirpy`,
  # este DEBE ser "/mi-blog-chirpy" (con la barra inclinada al inicio).
  # Si tu repositorio se llama `aricagua.github.io` (Sitio de Usuario), entonces `baseurl: ""` (vacío).

# ------------ The following options are not recommended to be modified ------------------
# (Deja el resto como está a menos que sepas exactamente lo que estás haciendo)
kramdown:
  footnote_backlink: "↩︎"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/ # Esto generará URLs como /tabs/about/ si tienes una pestaña "about"

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
